---
name: TorgetVest
configs:
  Debug: debug
  DebugSimulator: debug
  Release: release
options:
  usesTabs: false
fileGroups:
- XcodeGen
- TorgetVest
- TorgetVestTests
settings:
  base:
    ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
    CURRENT_PROJECT_VERSION: 202411251318
    DEVELOPMENT_TEAM: G9N5N6QUB2
    IPHONEOS_DEPLOYMENT_TARGET: 13.0
    MARKETING_VERSION: 1.2.0
    OTHER_SWIFT_FLAGS: "$(inherited) -Xfrontend -warn-long-function-bodies=200 -Xfrontend
      -warn-long-expression-type-checking=200"
    PRODUCT_NAME: TorgetVest
    PRODUCT_BUNDLE_IDENTIFIER: com.placewise.torget-vest
    DEVELOPMENT_LANGUAGE: 'no'
  configs:
    Debug:
      APP_DISPLAY_NAME: TorgetVest
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG BETA LOGS
      ONLY_ACTIVE_ARCH: 'YES'
    DebugSimulator:
      APP_DISPLAY_NAME: TorgetVest
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG BETA LOGS
      ONLY_ACTIVE_ARCH: 'NO'
      EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
    Release:
      APP_DISPLAY_NAME: TorgetVest
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: PROD LOGS
      VALIDATE_PRODUCT: true
